window.createDashboard({
  locale: 'zh-CN',
  chart: {
    line: '#2563eb',
    fill: 'rgba(37,99,235,0.10)',
    marker: '#2563eb',
  },
  text: {
    loadFailed: '加载失败',
    heroCompanies: '公司数量',
    heroFilings: '有最新财报',
    heroMarketData: '有市场数据',
    heroQuoteDate: '股价日期',
    sectorCompanies: (count) => `${count} 家`,
    allSectors: '全部行业',
    filterMetricPlaceholder: '指标',
    filterValuePlaceholder: '自定义数值，如 10B 或 500M',
    filterMetricLabel: (key) => ({
      marketCap: '市值',
      revenue: '营收规模',
      revenueGrowth: '营收增速',
      psRatio: 'PS',
      normalizedPe: '扣非市盈率',
      marketCapPayback: '5年市值回收率',
      forecastRevenue: '预测营收',
      forecastNetIncome: '预测净利润',
      forwardPe: '前瞻市盈率',
    }[key] || key),
    filterOperatorLabel: (key) => ({
      gt: '大于',
      gte: '大于等于',
      lt: '小于',
      lte: '小于等于',
      eq: '等于',
    }[key] || key),
    showing: (shown, total) => `显示 ${shown} / ${total} 家公司`,
    listPs: '市销率',
    listOpProfit: '营业利润',
    listCoreGrowth: '扣非增速',
    listNormalizedPe: '扣非市盈率',
    listMarketCapPayback: '5年回收率',
    aliases: '别名代码',
    previousClose: '上一交易日收盘价',
    marketCap: '市值',
    psRatio: '市销率',
    operatingProfit: '营业利润',
    feeAdjustedNetIncome: '扣费净利润',
    normalizedNetIncome: '扣非净利润',
    normalizedGrowth: '扣非净利润增速',
    normalizedGrowthGeomean: '3年扣非净利润几何增速',
    normalizedProjectionGrowth: '3年营收几何增速',
    normalizedPe: '扣非净利润市盈率',
    projectedFiveYearNormalizedNetIncome: '未来5年扣非净利润之和',
    marketCapPayback: '5年市值回收率',
    forecastRevenue: '预测营收',
    forecastNetIncome: '预测净利润',
    forwardPeRatio: '前瞻市盈率',
    peRatio: '市盈率',
    pbRatio: '市净率',
    annualRevenue: '年度营收',
    quarterlyRevenue: '季度营收',
    annualNetIncome: '年度净利润',
    freeCashFlow: '自由现金流',
    latestFiling: '最新财报',
    asOf: (date) => date ? `截止 ${date}` : '日期缺失',
    balanceSheetBasis: (form, date) => date ? `${form || 'SEC'}，申报日期 ${date}` : '缺少资产负债表口径',
    operatingMargin: (value) => value == null ? '缺少营业利润率口径' : `营业利润率 ${value}%`,
    proxyMetric: '基于 SEC 结构化科目生成的代理口径',
    marketCapPaybackFootnote: '未来5年扣非净利润预测总和 / 当前市值',
    marketCapPaybackProjectionFootnote: '作为未来5年扣非净利润投射的增长假设',
    forecastBasis: (year, sourceType, sourceName) => {
      if (!year && !sourceType && !sourceName) return '暂无预测口径';
      const parts = [];
      if (year) parts.push(`FY ${year}`);
      if (sourceType) parts.push(sourceType);
      if (sourceName) parts.push(sourceName);
      return parts.join(' / ');
    },
    earningsBasis: (fiscalYear) => fiscalYear ? `基于 FY ${fiscalYear} 每股收益` : '缺少利润口径',
    peUnavailable: '盈利为负或数据缺失',
    pbUnavailable: '净资产数据缺失',
    fiscalYear: (year) => year ? `FY ${year}` : '财年缺失',
    noData: (title) => `${title}：暂无数据`,
    range: (min, max) => `区间：${min} 到 ${max}`,
  },
});
