window.createDashboard({
  locale: 'zh-CN',
  chart: {
    line: '#2563eb',
    fill: 'rgba(37,99,235,0.10)',
    marker: '#2563eb',
  },
  text: {
    loadFailed: '加载失败',
    heroCompanies: '公司数量',
    heroFilings: '有最新财报',
    heroMarketData: '有市场数据',
    heroQuoteDate: '股价日期',
    sectorCompanies: (count) => `${count} 家`,
    allSectors: '全部行业',
    showing: (shown, total) => `显示 ${shown} / ${total} 家公司`,
    listPs: '市销率',
    listOpProfit: '营业利润',
    listCoreGrowth: '扣非增速',
    listNormalizedPe: '扣非市盈率',
    aliases: '别名代码',
    previousClose: '上一交易日收盘价',
    marketCap: '市值',
    psRatio: '市销率',
    operatingProfit: '营业利润',
    feeAdjustedNetIncome: '扣费净利润',
    normalizedNetIncome: '扣非净利润',
    normalizedGrowth: '扣非净利润增速',
    normalizedPe: '扣非净利润市盈率',
    peRatio: '市盈率',
    pbRatio: '市净率',
    annualRevenue: '年度营收',
    quarterlyRevenue: '季度营收',
    annualNetIncome: '年度净利润',
    freeCashFlow: '自由现金流',
    latestFiling: '最新财报',
    asOf: (date) => date ? `截止 ${date}` : '日期缺失',
    balanceSheetBasis: (form, date) => date ? `${form || 'SEC'}，申报日期 ${date}` : '缺少资产负债表口径',
    operatingMargin: (value) => value == null ? '缺少营业利润率口径' : `营业利润率 ${value}%`,
    proxyMetric: '基于 SEC 结构化科目生成的代理口径',
    earningsBasis: (fiscalYear) => fiscalYear ? `基于 FY ${fiscalYear} 每股收益` : '缺少利润口径',
    peUnavailable: '盈利为负或数据缺失',
    pbUnavailable: '净资产数据缺失',
    fiscalYear: (year) => year ? `FY ${year}` : '财年缺失',
    noData: (title) => `${title}：暂无数据`,
    range: (min, max) => `区间：${min} 到 ${max}`,
  },
});
