window.createDashboard({
  locale: 'en-US',
  chart: {
    line: '#2563eb',
    fill: 'rgba(37,99,235,0.10)',
    marker: '#2563eb',
  },
  text: {
    loadFailed: 'Failed to load',
    heroCompanies: 'Companies',
    heroFilings: 'With Latest Filing',
    heroMarketData: 'With Market Data',
    heroQuoteDate: 'Quote Date',
    sectorCompanies: (count) => `${count} names`,
    allSectors: 'All Sectors',
    showing: (shown, total) => `Showing ${shown} / ${total}`,
    listPs: 'P/S',
    listOpProfit: 'Op Profit',
    listCoreGrowth: 'Core NI YoY',
    listNormalizedPe: 'Normalized P/E',
    aliases: 'Aliases',
    previousClose: 'Previous Close',
    marketCap: 'Market Cap',
    psRatio: 'P/S',
    operatingProfit: 'Operating Profit',
    feeAdjustedNetIncome: 'Fee-Adjusted NI',
    normalizedNetIncome: 'Normalized NI',
    normalizedGrowth: 'Normalized NI YoY',
    normalizedPe: 'Normalized P/E',
    peRatio: 'P/E',
    pbRatio: 'P/B',
    annualRevenue: 'Annual Revenue',
    quarterlyRevenue: 'Quarterly Revenue',
    annualNetIncome: 'Annual Net Income',
    freeCashFlow: 'Free Cash Flow',
    latestFiling: 'Latest Filing',
    asOf: (date) => date ? `As of ${date}` : 'Date unavailable',
    balanceSheetBasis: (form, date) => date ? `${form || 'SEC'} filed ${date}` : 'Latest balance-sheet basis unavailable',
    operatingMargin: (value) => value == null ? 'Operating margin unavailable' : `Operating margin ${value}%`,
    proxyMetric: 'Proxy metric derived from SEC structured concepts',
    earningsBasis: (fiscalYear) => fiscalYear ? `Based on FY ${fiscalYear} earnings` : 'Latest earnings basis unavailable',
    peUnavailable: 'Negative or unavailable earnings',
    pbUnavailable: 'Unavailable book value',
    fiscalYear: (year) => year ? `FY ${year}` : 'Fiscal year unavailable',
    noData: (title) => `${title}: no data`,
    range: (min, max) => `Range: ${min} to ${max}`,
  },
});
